let shopItemsData = [{
    id:"sneaker1",
    name:"Adidas ",
    price: 120,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro1.webp",
},
{
    id:"sneaker2",
    name:"Adidas ",
    price: 100,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro1.webp",
},
{
    id:"sneaker3",
    name:"Adidas ",
    price: 150,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro3.webp",
},
{
    id:"sneaker4",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro4.webp",
},
{
    id:"sneaker5",
    name:"Adidas ",
    price: 195,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro4.webp",
},
{
    id:"sneaker6",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro9.webp",
},
{
    id:"sneaker7",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro10.webp",
},
{
    id:"sneaker8",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro8.webp",
},
{
    id:"sneaker9",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro9.webp",
},
{
    id:"sneaker10",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro10.webp",
},
{
    id:"sneaker11",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro11.jpg",
},
{
    id:"sneaker12",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro12.webp",
},
{
    id:"sneaker13",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro13.webp",
},
{
    id:"sneaker14",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro14.webp",
},
{
    id:"sneaker15",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro15.webp",
},
{
    id:"sneaker16",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro16.webp",
},
{
    id:"sneaker17",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro17.jpeg",
},
{
    id:"sneaker18",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro18.webp",
},
{
    id:"sneaker19",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro19.jpeg",
},
{
    id:"sneaker20",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro20.webp",
},
{
    id:"sneaker21",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro21.webp",
},
{
    id:"sneaker22",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro22.webp",
},
{
    id:"sneaker23",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro23.webp",
},
{
    id:"sneaker24",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro24.webp",
},
{
    id:"sneaker25",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro25.webp",
},
{
    id:"sneaker26",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro26.jpg",
},
{
    id:"sneaker27",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro27.webp",
},
{
    id:"sneaker28",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro28.webp",
},
{
    id:"sneaker29",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro29.jpg",
},
{
    id:"sneaker30",
    name:"Adidas ",
    price: 220,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing.",
    img: "sneakers/pro30.webp",
},
];